### ISSUE TITLE
Cannot use update method

### ISSUE THREAD

**Issue by ChrisDevinePimss** [highcharts/highcharts-angular#114]
### Describe the bug
Trying to toggle xAxis labels on/off but unable to do so

### Expected behavior
labels options to be set to true and chart redrawn 

### Demo
How it should work
https://codepen.io/ChrisDevine/pen/ErxLVe

#### Steps required to recreate the problem in the demo:
try calling the update method on Highcharts.charts[0] 

### Setup used
 - Angular version 6

**Comment by PimssTesting** [comment]
Update to version 7.

**Comment by KacperMadej** [comment]
Hi @ChrisDevinePimss 

Thank you for contacting us about the problem, but your bug report is incomplete.

Are you using the highcharts-angular wrapper? Are you using Angular? Those are not in your demo, so please add a demo or relevant code with both.

How are you changing the axis options? What happens when you try to change the axis options? Do you have any errors in browser console? All those questions and more will be answered through a demo showing the problem, but please check them and provide answers to confirm that we'll get the same results.

**Comment by PimssTesting** [comment]
Just FYI, this can be closed/removed as it was solved by updating to version 7.

**Comment by KacperMadej** [comment]
Thank you for the info @PimssTesting 
It would be nice to see this message from @ChrisDevinePimss , but I was going to close this issue due to inactivity anyway, so closing.

**Comment by ChrisDevinePimss** [comment]
@KacperMadej yes its fixed, sorry about the wait getting back to you
