### ISSUE TITLE
Hello world demo has invalid type for chartOptions

### ISSUE THREAD

**Issue by Waterstraal** [highcharts/highcharts-angular#134]
### Describe the bug
1. Adding proper types to the `chartOptions` property in the hello world example from the Readme will cause compile errors.
2. There is no proper type for the `Highcharts` property as far as I can tell.

### Expected behavior
1. The docs should provide a valid hello world example which is properly typed and compiles without errors. 

2. I should be able to add a valid type to the required `Highcharts` property.

### Demo

The following is written in the Readme:
```typescript
export class AppComponent {
  Highcharts = Highcharts;
  chartOptions = {
    series: [{
      data: [1, 2, 3]
    }]
  };
  ...
```

Adding the proper type will cause an error:
```typescript
export class AppComponent {
  Highcharts = Highcharts;
  chartOptions: Highcharts.Options = {
    series: [{
      data: [1, 2, 3]
    }]
  };
  ...
```
```
ERROR in src/app/chart/chart/chart.component.ts(13,14): error TS2322: Type '{ data: number[]; }' is not assignable to type 'SeriesAbandsOptions | SeriesAdOptions | SeriesAoOptions | SeriesApoOptions | SeriesAreaOptions | SeriesA
rearangeOptions | SeriesAreasplineOptions | SeriesAreasplinerangeOptions | ... 88 more ... | SeriesZigzagOptions'.
  Property 'type' is missing in type '{ data: number[]; }' but required in type 'SeriesZigzagOptions'.
```

Adding the type property will fix this:
```typescript
export class AppComponent {
  Highcharts = Highcharts;
  chartOptions: Highcharts.Options = {
    series: [{
      data: [1, 2, 3],
      type: 'line'
    }]
  };
  ...
```

**Comment by Waterstraal** [comment]
Regarding the second issue, I see  I can use a type guard: `typeof Highcharts`. Feels a bit like a workaround, and I would still prefer a proper regular type.

**Comment by KacperMadej** [comment]
Hi @Waterstraal 

Thank you for reporting about the problem.
This is a bug in the documentation, it should be updated to include those changes because of Highcharts changes in version 7.

The correct code should be with the `type` set on series options like you wrote.

The type for Highcharts should be like the app demo:
https://github.com/highcharts/highcharts-angular/blob/1bb7db5b0161e50fdfc3974fb3083098ce1642c6/src/app/app.component.ts#L51

with previously loaded Highcharts
https://github.com/highcharts/highcharts-angular/blob/1bb7db5b0161e50fdfc3974fb3083098ce1642c6/src/app/app.component.ts#L5

if you are using Highcharts version 7+, otherwise see the table here: https://github.com/highcharts/highcharts-angular/issues/107#issuecomment-452438614

**Comment by Phazzer** [comment]
I wish the highcharts-angular documentation could be extended with some more concrete explanations of the options, it is quite unclear to me exactly how the options play together. Some online-editor examples could make it easier for the community to communicate and understand issues. Don't get me wrong, it is a great library!
