### ISSUE TITLE
Error: Unexpected value 'HighchartsChartComponent' declared by the module 'IstWerteModule'. Please add a @Pipe/@Directive/@Component annotation.

### ISSUE THREAD

**Issue by mmuejde** [highcharts/highcharts-angular#15]
![screen shot 2018-02-19 at 13 42 16](https://user-images.githubusercontent.com/24757679/36378348-be3e03d6-157a-11e8-99e4-af79871f3837.png)

**Comment by mmuejde** [comment]
![screen shot 2018-02-19 at 13 42 59](https://user-images.githubusercontent.com/24757679/36378379-d423816c-157a-11e8-871a-223e0c00ac02.png)

**Comment by KacperMadej** [comment]
Hi,

Thank you for reporting about the problem.
I'm unable to recreate the error.

Please provide info about your OS, Node version, Angular version, Angular CLI version, NPM version and please add the files used for creating the app, so we could recreate the problem and test it.

**Comment by cloudmanic** [comment]
I am having the same issue.....

Angular CLI version (1.7.0)

Node: v8.7.0

Angular 5.2.6

NPM 5.4.2

Thanks!

**Comment by mcottingham** [comment]
I had the same issue.  I think that the index.js file is missing the export of the `HighchartsChartComponent`.  

I was able to resolve the file by modifying `node_modules/highcharts-angular/index.js` and adding the following line:
`export { HighchartsChartComponent } from './src/app/highcharts-chart.component';`

**Comment by cloudmanic** [comment]
I wish I could be more help here -- but I am not much of a node / npm expert. But this worked for me.

I just removed highcharts-angular from my package.json

and then copied this file

https://github.com/highcharts/highcharts-angular/blob/master/src/app/highcharts-chart.component.ts

into my own directories.

ie:` src/app/shared/highcharts/highcharts-chart.component.ts` 

Then I just imported it this way in my `app.module.ts`.

`import { HighchartsChartComponent } from './shared/highcharts/highcharts-chart.component';`

Lastly I deleted the stuff in `tsconfig.js`.

So I think the issue is how this package imports stuff or something. I have confirmed there is nothing wrong with the code in `highcharts-chart.component.ts`

**Comment by cloudmanic** [comment]
sounds like @mcottingham might have the  solution.

**Comment by KacperMadej** [comment]
Seems to me that newer Angular environment expects more strictly compiled files (to be used when loaded from NPM).
You can copy the component and use it in your environment as you have suggested.

To resolve this problem a compiled to js version of the module should be provided, test should be done for other versions.

**Comment by zorahrel** [comment]
+1

**Comment by Inurias** [comment]
+1

**Comment by grieddav** [comment]
+1

**Comment by pkoretic** [comment]
+1

**Comment by nm-a** [comment]
+1

**Comment by bhanu499** [comment]
+1

**Comment by rafszul** [comment]
i get the same error when running `ng build --aot`. it builds without a problem with JIT. I've tried all the proposed solutions and none of them let me build with `--aot` flag. any ideas or leads?

**Comment by tleveque23** [comment]
+1

Still no development on this one after a month?

**Comment by paulchill** [comment]
??

**Comment by KacperMadej** [comment]
Please try with standard install (as in the docs - https://github.com/highcharts/highcharts-angular#installing) and then after first error (or right after installing the `highcharts-angular` NPM package) change in `node_modules` folder the content of `highcharts-angular` to the content of the branch: https://github.com/highcharts/highcharts-angular/tree/v5-dev 

If this will work then the branch will become new master. As for now it was tested on few machines and the problem was resolved, but it would be better to run more tests. In the meantime you can try the `v5-dev` branch solution.

**Comment by KobiSh** [comment]
+1

**Comment by FatemeFazli** [comment]
+1

**Comment by Rai-Rai** [comment]
Hi,

replacing the content in highcharts-angular with the content of the v5-dev branch solved the issue of the error message
```ERROR in : Unexpected value 'HighchartsChartComponent in [...]/node_modules/highcharts-angular/index.js' declared by the module 'AppModule in [...]/src/app/app.module.ts'. Please add a @Pipe/@Directive/@Component annotation.```
For me. would be great if you could move this soon to the master and npm repository

**Comment by Ashwan91** [comment]
+1

**Comment by gdoge** [comment]
+1

**Comment by brannislav** [comment]
@KacperMadej can we have this fix in a official release so we could bump the Highcharts version.

**Comment by amandainnis** [comment]
so, just to be clear, highcharts-angular folder in node modules should be replaced by ENTIRE contents of v5 branch including the angular-cli.json file?

**Comment by amandainnis** [comment]
+1

**Comment by benjii** [comment]
+1

**Comment by PatrickTLK** [comment]
@rafszul I had the same problem when running ng build --prod (but not with ng serve or ng build). What I did was importing the HighchartsChartComponent directly from its .component.ts file like this:
`import { HighchartsChartComponent } from 'highcharts-angular/src/app/highcharts-chart.component';`

hope that helps you somehow

**Comment by benjii** [comment]
Thanks @KacperMadej - great to have this fixed. Sorry to be a pain, but when can we expect this to be pushed out to the NPM package?

**Comment by KacperMadej** [comment]
@benjii Today - within next few hours.
