### ISSUE TITLE
Some data points are not rendered after chartOptions update

### ISSUE THREAD

**Issue by IanNMarshall** [highcharts/highcharts-angular#154]
### Describe the bug
Some data points are not rendered after chartOptions update.

Note: This behavior started after [highcharts v7.1.0](https://github.com/highcharts/highcharts/releases/tag/v7.1.0), plugging in v7.0.3 on the stackblitz does make it work, however I'm posting here because I have not been able to reproduce outside of using the highcharts-angular wrapper.

### Expected behavior
Expected to look like it does on load only with different data. I am certainly not missing data in ng

### Demo
https://stackblitz.com/edit/angular-j1osjr

#### Steps required to recreate the problem in the demo:
1. on initial load everything looks correct.
![image](https://user-images.githubusercontent.com/10037915/62576041-07e4f380-b86a-11e9-8f21-1dab83b54467.png)
2. Click "RANDOMIZE" button to update chartOptions with new random data (calls exact same function as ngOnInit) and we are missing some data points. (Always the same ones (0, 1) -> (0, 6) ) 
![image](https://user-images.githubusercontent.com/10037915/62576157-4c708f00-b86a-11e9-9004-a10dc5a91ba2.png)

### Setup used
multiple, see stackblitz

**Comment by KacperMadej** [comment]
Hi @IanNMarshall 

Thank you for reporting about the problem.

For performance reasons when new data has the same length as old data then points are being (or at least an attempt is made) updated instead of destroying old points and creating new ones. This doesn't work well if x values are not unique like in the heatmap series type. To resolve this you could set `id` options with unique values (e.g. based on x + y position). Modifiying your code like this (line 20 in app.component.ts):

`data.push({x: i, y: j, value: Math.floor(100000*Math.random()), id:'p' + i +':' + j})`

fixes the problem with updates.

**Comment by IanNMarshall** [comment]
Works for me, thank you!
