### ISSUE TITLE
 CommonJS or AMD dependencies can cause optimization bailouts warning

### ISSUE THREAD

**Issue by fgoulet** [highcharts/highcharts-angular#227]
Since I have upgraded my app to Angular 10, I have this warning every time I build the app

highcharts-angular.js depends on 'highcharts'. CommonJS or AMD dependencies can cause optimization bailouts.

I know I can make this warning disappear but I'm just wondering if we could hope for a version of Highcharts optimized for ES Modules someday.

**Comment by mateuszkornecki** [comment]
@fgoulet Thanks for reporting the issue.

For now, there is nothing we can do about it. Highcharts are now in the middle of migration to the ES modules, so it might be solved in the future. 

I am closing this one since the similar ticket already exists on the Highcharts repository, here: https://github.com/highcharts/highcharts/issues/14183
