### ISSUE TITLE
Master-detail chart is not responsive at all

### ISSUE THREAD

**Issue by MoroccanGeek** [highcharts/highcharts-angular#248]
I'm using Master detail chart and it works fine, but it's not responsive at all, even at your own website (see video). I even tried resposivness from this example https://www.highcharts.com/demo/responsive , but nothing

https://user-images.githubusercontent.com/39879193/103093962-495f7580-45fc-11eb-8974-8d4dd38bbd45.mp4

**Comment by mateuszkornecki** [comment]
Hello @MoroccanGeek,

Thanks for contacting us!

For the future please keep in mind that it's a repository of `highcharts-angular` wrapper. That's a good place to report a bug related to the wrapper. If you have a highcharts general question please contact us through one of the support channels, see: https://www.highcharts.com/blog/support/

Answering your question - it looks like it was made on purpose. The master-detail chart is not responsive because the `chart.reflow` property is set to false. 

**API references:**
https://api.highcharts.com/highcharts/chart.reflow

**Live demo:**
https://jsfiddle.net/BlackLabel/fLy6vnmc/

Closing since it is not related to the `highcharts-angular` wrapper.

**Comment by MoroccanGeek** [comment]
Thank you. Sorry for that
