### ISSUE TITLE
Custom Series Name Is Not a valid value

### ISSUE THREAD

**Issue by Rossco8** [highcharts/highcharts-angular#265]
When adding a custom indicator / series, how do you use the new name in addSeries() when it is not a valid option from SeriesOptionType

You can see the error in this stackblitz
https://stackblitz.com/edit/highcharts-angular-stock-gui-a844pp?file=src/app/app.component.ts

**Comment by mateuszkornecki** [comment]
@Rossco8

It is happening because your custom series - `renko` does not exist in the Highcharts types. To fix the problem you could extend `Highcharts.SeriesOptionsType` with a custom `SeriesRenkoOptions` type and then cast your new series object to the `ExtendedSeriesOptionsType`.  

```typescript
type SeriesRenkoOptions = Omit<Highcharts.SeriesLineOptions, 'type'> & { type: 'renko' }; 

type ExtendedSeriesOptionsType = Highcharts.SeriesOptionsType & SeriesRenkoOptions;

...
    this.chartRef.addSeries({
      type: "renko",
      name: "Renko",
      id: "renko",
      data: ohlc
    } as ExtendedSeriesOptionsType);
```

**Live demo:**
https://stackblitz.com/edit/highcharts-angular-stock-gui-yhg2ax?file=src/app/app.component.ts

**Sources:**
https://www.typescriptlang.org/docs/handbook/utility-types.html#omittype-keys

Closing since the issue seems to be fixed.
