### ISSUE TITLE
Offline exporting doesn't work with custom buttons

### ISSUE THREAD

**Issue by lwensveen** [highcharts/highcharts-angular#268]
### Describe the bug
Offline exporting only works with the default menu, when you use a custom export solution like 

`this.chart.exportChart()`

it doesn't work

### Expected behavior
It does the export offline

### Demo
https://stackblitz.com/edit/highcharts-angular-basic-line-hdhllf?file=src%2Fapp%2Fapp.component.ts

#### Steps required to recreate the problem in the demo:
1. Click export
2. Check network tab

### Setup used
    "@angular/core": "^11.2.0",
    "highcharts": "9.0.0",
    "highcharts-angular": "^2.10.0",

**Comment by mateuszkornecki** [comment]
Hello @lwensveen, thanks for reporting the issue!

It must be related to your browser settings. In my case chrome was blocking downloading from stackblitz, but since I allowed chrome to download multiple files everything started working correctly and I was able to export your chart without problems.

Closing as everything seems to be working correctly.

**Comment by lwensveen** [comment]
@mateuszkornecki It does the export on the highcharts servers as you can see here:

![image](https://user-images.githubusercontent.com/4800388/107926597-3458f000-6f76-11eb-90d0-d030a1f07e0a.png)

**Comment by mateuszkornecki** [comment]
@lwensveen 

Oh, sorry it looks like I misunderstood you!

It is not working as you expected because function `exportChart` can't be used for offline exporting, it will always make a POST request. In order to export your chart offline, you need to use `exportChartLocal` instead.

**API references:**
https://api.highcharts.com/class-reference/Highcharts.Chart#exportChartLocal

**Live demo:**
https://stackblitz.com/edit/highcharts-angular-basic-line-7bluv3?file=src%2Fapp%2Fapp.component.ts
