### ISSUE TITLE
Improve demo app description

### ISSUE THREAD

**Issue by karolkolodziej** [highcharts/highcharts-angular#270]
### Describe the bug
Initializing demo project via `npm install` ---> `ng serve`  might cause an error. This method is not recommended in docs, however, in some cases, it's more natural.
```
Error: src/app/app.module.ts:5:39 - error TS2307: Cannot find module 'highcharts-angular' or its corresponding type declarations.
```

### Expected behaviour
Describe in docs how to prevent or solve that issue when it occurs.

**Comment by cbtum** [comment]
As a matter of interest, may I ask why there is a difference between `npm start` (which seems to call `ng serve` eventually and starting the application via `np serve`directly? Also, why did you decide to not include  "highcharts-angular": "^2.10.0", in the dependencies of package.json?

**Comment by mateuszkornecki** [comment]
The only difference is that `npm start` will build the `highcharts-angular` package for you. About including `highcharts-angular` in the `demo-app's package.json` we could totally do that. 

The reason why we are using the built package instead of the external dependency is pretty simple - thanks to that it's easier for us to check/test the master version that way. From the user perspective, the only difference is the initial command, after the package gets build, you can start it using just `ng serve`.

**Comment by cbtum** [comment]
I see, thanks for your explanation
