### ISSUE TITLE
Why custom indicator params are modified by getValues()

### ISSUE THREAD

**Issue by Rossco8** [highcharts/highcharts-angular#277]
When adding a custom indicator, my parameters are merged with the 'sma' parent params, I don't want the additional parameters as I need the params to match an API call

https://stackblitz.com/edit/highcharts-custom-indicator-issue?file=app/app.component.ts

See the console output for the issue

**Comment by karolkolodziej** [comment]
While defining a new indicator through the `seriesType` method, instead of using the object in `params`, pass the `undefined`.

PS. There is no need to perform the `chart.redraw()` after adding the series. The `addSeries` method will do it for you.
PS2. For general tech support, please use available support channels, see www.highcharts.com/support.

**Demo: https://stackblitz.com/edit/highcharts-custom-indicator-issue-4sgq8l**

**Comment by Rossco8** [comment]
Thanks @karolkolodziej
