### ISSUE TITLE
When series are hidden, the plotBand is still visible as a thin line 

### ISSUE THREAD

**Issue by Guzel738** [highcharts/highcharts-angular#280]
### Describe the bug
The plotbands remain visible as a thin line and translate to the beginning of the axis.

### Expected behavior
When you hide all of the series, the plotbands should be invisible.

### Demo
https://stackblitz.com/edit/angular-ivy-m8xiqc?file=src%2Fapp%2Fchild.component.ts

#### Steps required to recreate the problem in the demo:
Click on the legend to hide the series, and notice, that the plotBand remain visible with the width of 0.5 px at the beginning of the axis.

### Setup used
 - NodeJS version 15.10.0
 - Angular version 11.2.3
 - RxJS version 6.6.6

**Comment by mateuszkornecki** [comment]
Hello @Guzel738, thanks for your report!

The problem you reported is not related to the `highcharts-angular` wrapper. It looks like a `highcharts` bug that has been already reported and fixed (however the fix is not released yet). You can find more details about it, including a possible workaround in this thread: https://github.com/highcharts/highcharts/issues/15434.
