### ISSUE TITLE
Property 'marginRight' does not exist on type 'Chart'.

### ISSUE THREAD

**Issue by danieldavidraj** [highcharts/highcharts-angular#314]
Stackblitz link: [link](https://stackblitz.com/edit/angular-ivy-ssk8gw?file=src/app/app.component.ts)

![image](https://user-images.githubusercontent.com/59305023/152553703-82e6d08c-9102-459b-b041-085cdf9595a2.png)

**Comment by karolkolodziej** [comment]
If you take a closer look at the documentation you might learn how to create a custom interface by extending the existing one.
It might be sometimes necessary because not every property is publically available in the TS.

This interface might look something like this:
```TS
interface ExtendedChart extends Highcharts.Chart {
  marginRight: number
}
```
Then in the position you might cast it like this:
```TS
positioner: function (width, height, point) {
     var chart = this.chart as ExtendedChart,
...
```

For future reference, with questions like this please contact our support team through [available channels](https://www.highcharts.com/blog/support/).

**Documentation: https://github.com/highcharts/highcharts-angular#property-xxx-does-not-exist-on-type-yyy**
