### ISSUE TITLE
How to change fillColor only between two series point on mouse click and drag ?

### ISSUE THREAD

**Issue by Dhan3777** [highcharts/highcharts-angular#324]
https://jsfiddle.net/BlackLabel/745fL9a0

In above fiddle there is functionality to click and drag to get price difference between two point along with that rectangle is drawn over chart. But I want behaviour as per below website where color only get fill in area.

https://www.tickertape.in/stocks/reliance-industries-RELI?checklist=basic.

I have successfully modified the code for this but It's laggy Because, I am updating series and creating zones to change fillcolor between two point. Is there any otherway to do it ? I want exact click and drag behaviour as it is only website mentioned above please help

**Comment by karolkolodziej** [comment]
I can see a few options for how this can be archived:
1. Use zones which is quite simple to code but because you perform so many updates it might be laggy.
2. While selecting you can add [area series](https://jsfiddle.net/BlackLabel/qphma4ct/) but you might have a similar issue with performance.
3. Instead of adding `selectionRect` you can add a custom path that fits the chart line. 
This should work the smoothest but it will require some additional work to prepare/calculate this path.

For future reference, we use GitHub for tracking bugs and features. 
With questions like this please contact our support team through [available support channels.](https://www.highcharts.com/blog/support/)

**Comment by Dhan3777** [comment]
@karolkolodziej I have found solution https://jsfiddle.net/BlackLabel/57s8zr6d/ 

Now last thing that I need is updating series point colors only on hovered part (like this 
 https://www.tickertape.in/stocks/reliance-industries-RELI?checklist=basic.)

any thoughts?

**Comment by karolkolodziej** [comment]
It can work like in the demo below by adding a custom path based on the series path.
It only works now when you drop the mouse while hovering over the series.

Demo: https://jsfiddle.net/BlackLabel/r6ud3nqy/
