### ISSUE TITLE
How to use highstock indicators in angular 6?

### ISSUE THREAD

**Issue by sriramkp** [highcharts/highcharts-angular#35]
```
series: [{
          type: 'candlestick',
          id: 'aapl',
          name: 'AAPL Stock Price',
          data: data,
          zIndex: 1
        }, {
          type: 'pivotpoints',
          linkedTo: 'aapl',
          zIndex: 0,
          lineWidth: 1,
          dataLabels: {
            overflow: 'none',
            crop: false,
            y: 4,
            style: {
              fontSize: 9
            }
          }
        }, {
          type: 'macd',
          yAxis: 1,
          linkedTo: 'aapl'
        }]
```

I have formed the series like above, but I am getting the below error. Please let me know how to import or use the indicators.

Highcharts Error #17
The requested series type does not exist
This error happens when you are setting chart.type or series.type to a series type that isn't defined in Highcharts. A typical reason may be that your are missing the extension file where the series type is defined, for example in order to run an arearange series you need to load the highcharts-more.js file.

**Comment by sriramkp** [comment]
How to load the indicators module?

**Comment by pawelfus** [comment]
Hi @sriramkp 

Module `indicators` includes only SMA (see [docs](https://www.highcharts.com/docs/chart-and-series-types/technical-indicator-series)). Now you need to load chosen indicators:

```javascript
import * as HC_MACD from 'highcharts/indicators/macd';
HC_MACD(Highcharts);
```

Just like loading script in jsFiddle: http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/samples/stock/indicators/macd/

```
<script src="https://code.highcharts.com/stock/indicators/indicators.js"></script>
<script src="https://code.highcharts.com/stock/indicators/macd.js"></script>
```

**Comment by mitalthakkar** [comment]
As I want to add Indicators in my Angular 5 Project but https://www.npmjs.com/package/highstock-release

**Comment by pawelfus** [comment]
That's correct, package is deprecated, install Highcharts package: https://www.npmjs.com/package/highcharts

Docs about loading Highstock in NPM: https://www.highcharts.com/docs/getting-started/install-from-npm

Example:
```javascript
var Highcharts = require('highcharts/highstock');

// Load Highmaps as a module
require('highcharts/modules/map')(Highcharts);
```

**Comment by mitalthakkar** [comment]
Hi,
I had tried to install as per your instructions.But I got an error:

highcharts.js:9 Uncaught Error: Highcharts error #13: www.highcharts.com/errors/13
    at a.error (highcharts.js:9)
    at a.Chart.getContainer (highcharts.js:244)
    at a.Chart.firstRender (highcharts.js:259)
    at a.Chart.init (highcharts.js:236)
    at a.Chart.getArgs (highcharts.js:235)
    at new a.Chart (highcharts.js:235)
    at Object.a.chart (highcharts.js:235)
    at eval (app.component.ts:22)
    at Object.../../../../../src/app/app.component.ts (main.bundle.js:28)
    at __webpack_require__ (inline.bundle.js:55)

**Comment by KacperMadej** [comment]
Hi @mitalthakkar 

The error is about missing container for the chart. Please check if there's any typo when setting container, renderTo option is used (it shouldn't when using the highcharts-angular wrapper) or if the container is set dynamically or in any other way that could cause a race problem - when chart is created before it's container exists.

You could load highcharts.src.js instead of highcharts.js for readable code and check with opened browser console and stop at error to debug the issue. Then you should be able to check where is the container. Please try to recreate the problem in a live demo or provide another way for us to debug or help you with debugging of the problem. You could clone this repository and modify it's demo app - next share your branch or files. Technical support cases might be easier to resolve through [e-mail](https://www.highcharts.com/support) - easier communication and files exchange, and we are trying to keep GitHub mainly for bugs.

**Comment by mitalthakkar** [comment]
Hello,
I tried a lot all library and finally found the solution which is at below. Please find below link for the solution if any one needed.

https://github.com/mitalthakkar/candlestick-indicators

It is Angular 5 highcharts candle stick example with indicators.
