### ISSUE TITLE
The chart instance gets destroyed on ngOnDestroy but not emitted

### ISSUE THREAD

**Issue by Kisters-BS** [highcharts/highcharts-angular#365]
### Describe the bug
The chart instance gets destroyed on ngOnDestroy but not emitted. Therefore if the highcharts-chart component was destroyed, the component which uses it still has the old instance of chart and can call functions which will throw errors.

### Expected behavior
The chart instance should be emitted.

### Demo
https://stackblitz.com/edit/highcharts-angular-line-shxbz5?file=src%2Fapp%2Fapp.component.ts

#### Steps required to recreate the problem in the demo:
1. Use the highcharts-chart component
2. Destroy the highcharts-chart component
3. Use a function of chart instance
4. Get error

### Setup used
See stackblitz

**Comment by karolkolodziej** [comment]
Hi @Kisters-BS!

Thank you for reporting the issue!

**Comment by stevethemacguy** [comment]
@karolkolodziej In highcharts-angular v3.1.2, a valid `chartInstance` is emitted only after a chart is created. If 2 charts are created, it fires twice.

In v4.0.0, it now emits an extra time with a null object for each chart `onDestroy`. This breaks our app since we expect to create charts when `addInstance` fires. I can ignore the extra null `chartInstance` emits, but this doesn't seem like the desired behavior.

What is the benefit of returning null objects? Thanks!

**Comment by karolkolodziej** [comment]
@stevethemacguy as @Kisters-BS explained originally:
> the component which uses it still has the old instance of chart and can call functions which will throw errors.

IMO it is easier to properly handle the lifetime of the `higcharts-angular` when `null` is emitted.

**Comment by stevethemacguy** [comment]
@karolkolodziej. Ok, thanks for the quick response!
