### ISSUE TITLE
Stacked Area symbol bug

### ISSUE THREAD

**Issue by ogabz12345** [highcharts/highcharts-angular#367]
> For general tech support, please see www.highcharts.com/support.
> Please report only issues about `highcharts-angular` wrapper or content of this repository.
> For general issues with Highcharts and TypeScript the correct repository to report such issues is [main Highcharts repository](https://github.com/highcharts/highcharts/issues).

### Describe the bug
Area Series Marker Symbol is not applied to Legend item for Area Series 

### Expected behavior
If I set a marker.symbol or not(which randomly defaults to the available symbols) to e.g. square the same marker as on the chart will be shown on the legend.

### Demo
[Demo](https://stackblitz.com/edit/highcharts-angular-update-optimal-way-jtxppt?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html)

### Setup used
NodeJS version - v18.5.0
Angular version - v15.2
TypeScript version - v4.9.4
 Highcharts version - v10.3.3,
 Highcharts-angular version - v3.1.2,
etc.

Related to [issue-1](https://github.com/highcharts/highcharts/issues/7771) and [issue-2](https://github.com/highcharts/highcharts/issues/17388)

**Comment by Vazonik** [comment]
Hello @ogabz12345,

Thanks for reporting this issue!

As you can read in the discussion under the issues you submitted, this is not a bug, moreover, it does not apply strictly to Highcharts Angular integration, but results strictly from Highcharts Core.

Moreover, since HC v11.0.1, an option [`legendSymbol`](https://api.highcharts.com/highcharts/series.line.legendSymbol) has been introduced that allows you to enable line series mode in markers in the legend. See the [demo](https://stackblitz.com/edit/highcharts-angular-update-optimal-way-skgew2?file=src%2Fapp%2Fapp.component.ts,package.json).

**Comment by ogabz12345** [comment]
Thanks for clarifying.
