### ISSUE TITLE
Zoom reset issue

### ISSUE THREAD

**Issue by wojciechtryba-td** [highcharts/highcharts-angular#387]
### Description
I create a chart with 2 scatter series. One contains random data and the other one represents data selection. I zoom very close to any point and click on it. Then, I reset zoom and there an issue appears. The view isn't adjusted to display all data. The view can be reset by resizing the window or by selecting another point. The issue doesn't appear when HighchartsBoost isn't included.

### Expected behavior
Reseting zoom should set chart view to display all data.

### Demo
[Live demo](https://stackblitz.com/edit/stackblitz-starters-5t2yfz?file=src%2Fchart%2Fchart.component.ts)

#### Steps required to recreate the problem in the demo:
1. Zoom multiple times to any point
2. Click on this point so a selection appears
3. Click 'Reset zoom'

### Setup used
 - NodeJS version - 18.20.3
 - Angular version - 18.0.0
 - TypeScript version - 5.4.0
 - Highcharts - 11.4.0
 - Highcharts-Angular - 4.0.0

**Comment by karolkolodziej** [comment]
Hi @wojciechtryba-td! 
I'm sorry that it took me so long to reply. 

The issue isn't in the wrapper but it is a regression introduced in v11.3.0 (the last working version v11.2.0) of the main Highcharts library.
I reported it here: https://github.com/highcharts/highcharts/issues/21551

For now, until the issue is solved I suggest using the older version without this bug. 
I haven't found any other smart, reasonable workaround for it.
