### ISSUE TITLE
How to include moment-timezone?

### ISSUE THREAD

**Issue by sjerman** [highcharts/highcharts-angular#51]
Want to set the display timezone. Tried:

```
import * as moment from 'moment-timezone';
import * as Highcharts from 'highcharts';
import * as HighchartsMore from 'highcharts/highcharts-more.src.js';
import * as HighchartsExport from 'highcharts/modules/exporting.src.js';
HighchartsExport(Highcharts);
HighchartsMore(Highcharts);
moment(Highcharts);
```
 Still get:  `Highcharts error #25: www.highcharts.com/errors/25` on console.

How do I import?

Steve

**Comment by wchmiel** [comment]
Hi sjerman,

We've reported that problem as issue on our github [https://github.com/highcharts/highcharts/issues/8661](url).

But I've got workaround for you, firstly you have to import both moment and moment-timezone dependencies. Then set moment as window.moment, so Highcharts will be able to find it and initialise moment-timezone. Example:

```
import * as Highcharts from "highcharts";
import * as Moment from "moment";
import * as mTZ from "moment-timezone";

window.moment = Moment;
mTZ()
```

Online example: [https://codesandbox.io/s/l4yx6okpk7](url).

I hope it is clear for you now.

Best regards.

**Comment by sjerman** [comment]
Thanks! that helps a lot.

**Comment by envynoiz** [comment]
Hello! I just want to know if there are updates regarding this topic, I mean the provided or temporal solution does not work if you are in an Angular's service, please is there another way to do it?

Note: I tried to see the online example but it does not work anymore and also I can not find the reported issue in order to track the updates about it.
