### ISSUE TITLE
highcharts is loaded before angular-highcharts component is loaded: www.highcharts.com/errors/16 is thrown

### ISSUE THREAD

**Issue by tiho2** [highcharts/highcharts-angular#52]
Angular 2+ is used for new part of Spring MVC application where Highcharts is used. Later, highcharts charting (angular-highcharts) is added to new components written in angular 2+ technology. The same Highcharts 6 version is used at both sides.
At the time angular charting component is initialized Highcharts is already loaded in web page and following Uncaught Error: Highcharts error #16: www.highcharts.com/errors/16 is thrown.

Highcharts is not reloaded by angular component and H.error(code, true) is executed. What is the best way to resolve this conflict?
Should additional Highcharts_X global variable for legacy web application be created? I don't prefer this approach because it is productively used by Higcharts and then it should be changed in the source code at many places.(?)

Is it possible to tell angular-higcharts that the library is already loaded and to use that one?
Or to let it be reloaded without breaking JS with the error?

**Comment by gregjacobs** [comment]
Hey @tiho2, make sure you are loading Highcharts on a global level in the same way you are loading it up in order to pass it to highcharts-angular.

So for example, if you are currently pulling in Highcharts with a <script> tag, then remove that tag and put this somewhere in your project (maybe a file called vendor.ts):

```ts
import * as Highcharts from 'highcharts';

window.Highcharts = Highcharts;  // expose as global
```

**Comment by KacperMadej** [comment]
Hi @tiho2 

You are writing about `angular-highcharts` and this is `highcharts-angular` repository.

If you made a typo and have a problem with `highcharts-angular`, then please provide more details about the problem. Please provide a live demo or another way to recreate the problem.

If you are using mixed content, so Angular is not loaded and Highcharts are loaded through script tag in HTML code then the Angular wrapper for Highcharts is not need and you could use pure JavaScript code using only Highcharts - https://www.highcharts.com/docs/getting-started/installation

**Comment by tiho2** [comment]
Hi @KacperMadej ,

I see, this is wrong repo. Actually angular2-highcharts is used by Angular components.
The case is that the application is big, rewrite can not an option for now. New components are written in Angular 2+, and the result is that highcharts are needed in both parts.

**Comment by KacperMadej** [comment]
https://www.highcharts.com/support

For general Highcharts support please contact [technical support](https://www.highcharts.com/support) with a demo or relevant part of code that will allow checking what is the source of the problem you have. `angular2-highcharts` is not an official wrapper, so there might be some limits for Highcharts technical support. However, we are trying to help as long as the problem is connected to Highcharts.

https://www.highcharts.com/support

**Comment by gregjacobs** [comment]
@tiho2 If you are running Angular 2+ then you are likely already using a *module loader*, which allows you to specify modules and import statements and then bundles them up in the correct format for the web. This does not require browser support of modules. Your project is likely using webpack/angular-cli or systemjs, which are both module loaders/bundlers.

If you specify the same exact version of Highcharts in your project's package.json that angular2-highcharts is using, then they should use the same Highcharts instance on your page *assuming* that you loaded your global Highcharts instance in the module loader/bundler (I.e. `import` or `require` statement) rather than with a <script> tag.

Your best bet actually is to just switch from using angular2-highcharts to using this package instead (highcharts-angular), where you can pass in the shared Highcharts constructor whether it's from an `import` statement or if it's just `window.Highcharts`

**Comment by tiho2** [comment]
>  ...where you can pass in the shared Highcharts constructor...
That could be the case.  
Legacy app forces that the lib is loaded via script tag before the Angular component is initialized. And later Angular component should take global Highcharts instead to create new instance.
