### ISSUE TITLE
Drillup button is not removed when options object is updated

### ISSUE THREAD

**Issue by Getz85** [highcharts/highcharts-angular#61]
I don't know if the issue come from Highcharts, the highcharts-angular module or how I use them.

I've got a page with a menu which change the options of a chart.
Some of the options contains drilldown objects, but not the others.

When a drilldown object is selected, the drillup button is displayed.

But if I change the charts options object, the drillup button is not removed.

Here is a [Stackblitz](https://stackblitz.com/edit/angular-go9w7i) reproducing the issue. Fisrt, click on the  "others" slice, then on "Change options" button: the "back" button is still displayed and clickable.

**Comment by KacperMadej** [comment]
Hi @Getz85 

Thank you for reporting about the case.

The problem is caused by chart update called during drill down. It's possible to recreate in pure Highcharts - http://jsfiddle.net/BlackLabel/17cu5xjk/

Moving the issue there, as this is a general Highcharts problem and marking this issue as a duplicate.
https://github.com/highcharts/highcharts/issues/8839

**Workaround:** Do not call the update before going back to the top level in a chart that was drilled down.
