### ISSUE TITLE
Using series type 'errorbar' throws error #17

### ISSUE THREAD

**Issue by abatkins** [highcharts/highcharts-angular#79]
Error 17:
The requested series type does not exist
This error happens when you are setting chart.type or series.type to a series type that isn't defined in Highcharts. A typical reason may be that your are missing the extension file where the series type is defined, for example in order to run an arearange series you need to load the highcharts-more.js file.

It appears the highcharts-more module needs to be loaded. Is there documentation on how to do this with an angular way of doing this? I couldn't find a non-deprecated angular-more npm module. 

It appears to be the same issue described in this stack overflow page (which was never resolved):
https://stackoverflow.com/questions/48643333/how-to-import-highchart-more-into-angular-4-project

**Comment by KacperMadej** [comment]
Hi @abatkins 

Why are you looking for angular-more module if the problem is with lack of Highcharts module (highcharts-more to be precise)?
Load highcharts-more as [any other module](https://github.com/highcharts/highcharts-angular#to-load-a-module).

The questions on Stack Overflow was answered by Paweł and it was resolved. The answer was not accepted, but this is up to the user asking the question, so there's not much we could do.
