### ISSUE TITLE
Pie charts not redrawn correctly

### ISSUE THREAD

**Issue by pgschr** [highcharts/highcharts-angular#99]
This problem happens when I need to redraw a Pie chart enabling/disabling for example styles such as donut/semicircles. Every time I change the chart and set `updateFromInput = true` the chart is redrawn, but incorrectly. See example [here](https://codesandbox.io/s/jl3x14n0m5), the chart is first redrawn full, then click on "Change to Semi" to change it to semicircle. That works fine, but it only works the first time. Click on "Back to Full" to see the full chart again and you'll see it's redrawn incorrectly. 

Again, this happens with many settings in the pie chart, they are not restored when the chart needs to be redrawn.

**Comment by KacperMadej** [comment]
Hi, thanks for contacting us! You've posted to our issue tracker. For general tech support, please see www.highcharts.com/support.

P.S.
You have set some options in a one update, so you will have to set them back to default in the second update - otherwise there's no reason for Highcharts to reset the options. The most visible change could be done by adding:

```ts
          startAngle: 0,
          endAngle: 360
```
 into `setChart1`'s `plotOptions.pie`.
